# min and max period of seismograms
min_period: 50.0
max_period: 100.0

# config parameters
ipower_costaper: 10
taper_percentage: 0.15
taper_type: 'hann'
use_cc_error: True

# for postprocessing
interp_delta: 0.1425
interp_npts: 42000
