# min and max period(unit: second)
min_period: 50.0
max_period: 100.0

# adjoint config parameter
taper_percentage: 0.15
taper_type: 'hann'
use_cc_error: False

# for postprocessing
interp_delta: 0.1425
interp_npts: 42000
